# Generated by Django 2.2.7 on 2019-11-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=14)),
                ('genero', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=14)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
