# Generated by Django 2.2.7 on 2019-11-21 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm_genero', models.CharField(max_length=10, verbose_name='Gênero')),
                ('sg_genero', models.CharField(max_length=4, verbose_name='Abrev. gênero')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='genero',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=45, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=14, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fk_genero',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cliente.Genero', verbose_name='Gênero'),
        ),
    ]
